/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project.bai3sw;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Long NH
 */
public class FS extends javax.swing.JFrame {

    /** Creates new form FS */
    public FS() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstLeft = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstRight = new javax.swing.JList<>();
        btnThem = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnAR = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnAL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstLeft.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Bóng Đá", "Bóng Chuyền", "Bóng Rổ", "Cầu Lông", "Bơi Lội" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstLeft);

        jScrollPane2.setViewportView(lstRight);

        btnThem.setText("+");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnR.setText(">");
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });

        btnAR.setText(">>");
        btnAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnARActionPerformed(evt);
            }
        });

        btnL.setText("<");
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });

        btnAL.setText("<<");
        btnAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnALActionPerformed(evt);
            }
        });

        jLabel1.setText("DS Môn Thể Thao");

        jLabel2.setText("Môn Yêu Thích");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnR, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnR)
                        .addGap(16, 16, 16)
                        .addComponent(btnAR)
                        .addGap(18, 18, 18)
                        .addComponent(btnL)
                        .addGap(18, 18, 18)
                        .addComponent(btnAL)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThem)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        JFrame f;
        f = new JFrame();
        String name=JOptionPane.showInputDialog(f,"Nhập môn thể thao");
        
        ListModel dsTen= lstLeft.getModel();
        ArrayList<String> arrTen = new ArrayList<>();
        int i=0;
        for (i=0; i<dsTen.getSize(); i++)
        {   
            String ten =dsTen.getElementAt(i).toString();
            arrTen.add(ten);
        }
        arrTen.add(name);
        String[] mTen = arrTen.toArray(new String[arrTen.size()]);
        lstLeft.setListData(mTen);
       
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
        //Lấy về Model
        ListModel mLeft = lstLeft.getModel();
        ArrayList<String> arrLeft = new ArrayList<>();
        ListModel mRight= lstRight.getModel();
        ArrayList<String> arrRight = new ArrayList<>();
        //Lấy vị trí đc chọn
        int j = lstLeft.getSelectedIndex();
        //Xử lý danh sách phải
        for (int i=0; i<mRight.getSize(); i++)
        {   
            String ten =mRight.getElementAt(i).toString();
            arrRight.add(ten);
        }
        arrRight.add(mLeft.getElementAt(j).toString());
        String[] dataRight = arrRight.toArray(new String[0]);
        lstRight.setListData(dataRight);
        //Xử lý danh sách trái
        for (int i=0; i<mLeft.getSize(); i++)
        {   
            String ten =mLeft.getElementAt(i).toString();
            arrLeft.add(ten);
        }
        //Xóa Khỏi array Trái
        arrLeft.remove(mLeft.getElementAt(j));
        String[] dataLeft = arrLeft.toArray(new String[0]);
        lstLeft.setListData(dataLeft);
        
       
    }//GEN-LAST:event_btnRActionPerformed

    private void btnARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnARActionPerformed
        //Lấy về Model
        ListModel mLeft = lstLeft.getModel();
        ListModel mRight= lstRight.getModel();
        ArrayList<String> arr = new ArrayList<>();
        //Xử lý danh sách phải
        for (int i=0; i<mRight.getSize(); i++)
        {   
            String ten =mRight.getElementAt(i).toString();
            arr.add(ten);
        }
        //Xử lý danh sách Trái
        for (int i=0; i<mLeft.getSize(); i++)
        {   
            String ten =mLeft.getElementAt(i).toString();
            arr.add(ten);
        }
        String[] data = arr.toArray(new String[0]);
        lstRight.setListData(data);
        arr.removeAll(arr);
        data = arr.toArray(new String[0]);
        lstLeft.setListData(data);
    }//GEN-LAST:event_btnARActionPerformed

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        //Lấy về Model
        ListModel mLeft = lstLeft.getModel();
        ArrayList<String> arrLeft = new ArrayList<>();
        ListModel mRight= lstRight.getModel();
        ArrayList<String> arrRight = new ArrayList<>();
        //Lấy vị trí đc chọn
        int j = lstRight.getSelectedIndex();
        //Xử lý danh sách trái
        for (int i=0; i<mLeft.getSize(); i++)
        {   
            String ten = mLeft.getElementAt(i).toString();
            arrLeft.add(ten);
        }
        arrLeft.add(mRight.getElementAt(j).toString());
        String[] dataLeft = arrLeft.toArray(new String[0]);
        lstLeft.setListData(dataLeft);
        //Xử lý danh sách phải
        for (int i=0; i<mRight.getSize(); i++)
        {   
            String ten =mRight.getElementAt(i).toString();
            arrRight.add(ten);
        }
        
        //Xóa Khỏi array Phải
        arrRight.remove(mRight.getElementAt(j));
        String[] dataRight = arrRight.toArray(new String[0]);
        lstRight.setListData(dataRight);
    }//GEN-LAST:event_btnLActionPerformed

    private void btnALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnALActionPerformed
        ListModel mLeft = lstLeft.getModel();
        ListModel mRight = lstRight.getModel();
        ArrayList<String> arr = new ArrayList<>();
        for(int i=0;i<mLeft.getSize(); i++){
            String ten = mLeft.getElementAt(i).toString();
            arr.add(ten);
        }
        for(int i=0;i<mRight.getSize();i++){
            String ten = mRight.getElementAt(i).toString();
            arr.add(ten);
        }
        String[] data = arr.toArray(new String[0]);
        lstLeft.setListData(data);
        arr.removeAll(arr);
        data = arr.toArray(new String[0]);
        lstRight.setListData(data);    
    }//GEN-LAST:event_btnALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAL;
    private javax.swing.JButton btnAR;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstLeft;
    private javax.swing.JList<String> lstRight;
    // End of variables declaration//GEN-END:variables

}
